services:
  postgres:
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "9876:5432"
  server:
    image: ghcr.io/${GITHUB_USER}/gourmet-server
    environment:
      - CLERK_SECRET_KEY
      - LLM_BASE_URL=https://api.studio.nebius.com/v1/
      - LLM_MODEL=Qwen/Qwen2.5-32B-Instruct
      - LLM_API_KEY
      - DATABASE_URL=postgresql+asyncpg://postgres:$POSTGRES_PASSWORD@postgres:5432
    depends_on:
      - postgres
      - ollama
  client:
    image: ghcr.io/${GITHUB_USER}/gourmet-client
    ports:
      - "80:3000"
    environment:
      - CLERK_SECRET_KEY
      - SERVER_URL=http://server:8000
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - server
