services:
  postgres:
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  server:
    image: ghcr.io/azizi-a/gourmet-server
    ports:
      - "8000:8000"
    environment:
      - CLERK_SECRET_KEY
      - DATABASE_URL=postgresql+asyncpg://postgres:$POSTGRES_PASSWORD@postgres:5432
    depends_on:
      - postgres
  client:
    image: ghcr.io/azizi-a/gourmet-client
    ports:
      - "80:3000"
    environment:
      - CLERK_SECRET_KEY
      - SERVER_URL=http://server:8000
    depends_on:
      - server
