"""add content ratings

Revision ID: 930463ae22db
Revises: eea9494188d5
Create Date: 2025-03-19 16:03:38.879339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '930463ae22db'
down_revision: Union[str, None] = 'eea9494188d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_content_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_user_content_rating')
    )
    op.add_column('content', sa.Column('content_type', sa.String(), nullable=True))
    op.add_column('content', sa.Column('media', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'media')
    op.drop_column('content', 'content_type')
    op.drop_table('user_content_ratings')
    # ### end Alembic commands ###
