"""add source_id to ingestion_jobs table

Revision ID: ae600ec88b8b
Revises: 1a72e16b9aae
Create Date: 2025-03-22 17:13:47.152404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'ae600ec88b8b'
down_revision: Union[str, None] = '1a72e16b9aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_jobs', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ingestion_jobs', 'sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingestion_jobs', type_='foreignkey')
    op.drop_column('ingestion_jobs', 'source_id')
    # ### end Alembic commands ###
