"""Initial migration

Revision ID: eea9494188d5
Revises:
Create Date: 2025-03-18 18:59:05.794600

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "eea9494188d5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "content",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("title", sa.String(), nullable=True),
    sa.Column("url", sa.String(), nullable=True),
    sa.Column("description", sa.String(), nullable=True),
    sa.Column("source_id", sa.Integer(), nullable=True),
    sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column("date", sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("url"),
  )
  op.create_table(
    "ingestion_jobs",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
    sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
    sa.Column("status", sa.String(), nullable=True),
    sa.Column("items_processed", sa.Integer(), nullable=True),
    sa.Column("items_added", sa.Integer(), nullable=True),
    sa.Column("error_message", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "sources",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("url", sa.String(), nullable=True),
    sa.Column("source_type", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("url"),
  )
  op.create_table(
    "users",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.PrimaryKeyConstraint("id"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("users")
  op.drop_table("sources")
  op.drop_table("ingestion_jobs")
  op.drop_table("content")
  # ### end Alembic commands ###
